package com.bink.wallet.utils.enums

enum class LinkStatus(val status: Float) {
    STATUS_LINKED_TO_SOME_OR_ALL(2.1f),
    STATUS_LINKABLE_NO_PAYMENT_CARDS(2.2f),
    STATUS_LINKABLE_NO_PAYMENT_CARDS_LINKED(2.3f),
    STATUS_LINKABLE_GENERIC_ERROR(2.4f),
    STATUS_LINKABLE_REQUIRES_AUTH(2.5f),
    STATUS_LINKABLE_REQUIRES_AUTH_PENDING(2.6f),
    STATUS_LINKABLE_REQUIRES_AUTH_PENDING_FAILED(2.7f),
    STATUS_UNLINKABLE(2.8f)
}