package com.bink.wallet.utils.enums

enum class LoginStatus(val status: Double) {
    STATUS_LOGGED_IN_HISTORY_AVAILABLE(1.1),
    STATUS_LOGGED_IN_HISTORY_UNAVAILABLE(1.2),
    STATUS_NOT_LOGGED_IN_HISTORY_UNAVAILABLE(1.3),
    STATUS_NOT_LOGGED_IN_HISTORY_AVAILABLE(1.4),
    STATUS_LOGIN_UNAVAILABLE(1.5),
    STATUS_LOGIN_FAILED(1.6),
    STATUS_LOGIN_PENDING(1.7),
    STATUS_SIGN_UP_FAILED(1.8),
    STATUS_SIGN_UP_PENDING(1.9),
    STATUS_REGISTER_GHOST_CARD_FAILED(1.10),
    STATUS_REGISTER_GHOST_CARD_PENDING(1.11),
    STATUS_CARD_ALREADY_EXISTS(1.12)
}


