package com.bink.wallet.utils

object MixpanelEvents {
    const val BRAND_NAME = "Brand name"
    const val VALUE_UNKNOWN = "Unknown"
    const val ERROR = "Error"
    const val LPS_STATUS = "Status"
    const val LC_ID = "Loyalty card ID"
    const val METHOD = "Method"
    const val LOGIN_PASSWORD = "Password"
    const val LOGIN_ML = "Magic link"
    const val LOYALTY_CARD_ADD = "Loyalty card add"
    const val LOYALTY_CARD_ADD_FAIL = "Loyalty card add failed"
    const val LOYALTY_CARD_REORDER = "Loyalty card manually reordered"
    const val LOYALTY_CARD_SCRAPE_STATUS = "Local points collection status"
    const val LOYALTY_CARD_DETAIL = "Loyalty card detail viewed"
    const val LPS_SUCCESS = "Local points collection succeeded"
    const val LPS_FAIL = "Local points collection failed"
    const val LPS_REASON = "Reason"
    const val FORGOT_PASS = "Forgotten Password"
    const val ONBOARDING_STARTED = "Onboarding Started"
    const val ONBOARDING_COMPLETE = "Onboarding Complete"
    const val LOGOUT = "User logged out"
    const val TOTAL_CARDS_PROP = "Total Cards"
    const val TOTAL_PLL_CARDS_PROP = "Total PLL Cards"
    const val TOTAL_LINKED_PLL_CARDS_PROP = "Total Linked PLL Cards"
    const val TOTAL_DUPE_CARDS_PROP = "Total Duplicate Cards"
    const val BARCODE_VIEWED = "Barcode Viewed"
    const val ROUTE = "Route"
    const val ROUTE_WALLET = "Wallet"
    const val ROUTE_LCD = "Loyalty Card Detail"
    const val CARD_DELETED = "Card Deleted"
    const val BARCODE_ISSUE = "Barcode screen issue reported"
}